name: tests

on:
  push:
    branches-ignore:
      - "*docs*"

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ '{{' }} matrix.python-version {{ '}}' }} 🐍
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Prepare Test environment
        run: |
          # install packages needed for testing
          pip install -r test_requirements.txt
      - name: Lint with pylint
        run: |
          pip install pylint
          # Search for actual errors
          pylint src/*/*.py -E
          # For warnings instead return always zero
          pylint src/*/*.py --exit-zero
      - name: Test package
        run: |
          # run tests
          pytest tests
{%- if cookiecutter.upload_to_codecov %}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ '{{' }} secrets.CODECOV_TOKEN {{ '}}' }}
          file: ./coverage.xml
          flags: tests
          name: codecov-umbrella
          fail_ci_if_error: true
{%- endif %}
